### ISSUE TITLE
目前的这个版本貌似用不了

### ISSUE THREAD

**Issue by mingyi0** [Hasal/dzhops#3]
您好，您删除common后的这个版本，还有很多views对common包的依赖，我手动清除了common相关的import还是报错。。。
最新报错是：
Reverse for 'module_deploy' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

Reverse for 'module_deploy' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
`1  {% extends "base.html" %}
2   {% block title %}移动终端自动化运维平台{% endblock %}
3   {% block nav %}
4       <li class="active"><a href="{% url 'index' %}"><i class="glyphicon glyphicon-dashboard"></i> 仪表盘<span class="sr-only">(current)</span></a></li>
5       <li><a href="{% url 'host_list' %}"><i class="glyphicon glyphicon-th-list"></i> 主机列表</a></li>
6       <li><a href="{% url 'module_deploy' %}"><i class="glyphicon glyphicon-th-large"></i> SaltStack</a></li>
7       <li><a href="{% url 'replace_data' %}"><i class="glyphicon glyphicon-repeat"></i> 数据修复</a></li>
8       <li><a href="{% url 'key_list' %}"><i class="glyphicon glyphicon-tags"></i> MinionKeys</a></li>
9       <li><a href="{% url 'record' %}"><i class="glyphicon glyphicon-floppy-disk"></i> 操作记录</a></li>
10  {% endblock %}
11  {% block content %}
12      <h5 class="page-header">
13          <ol class="breadcrumb">
14              <li class="active">仪表盘</li>
15          </ol>
16      </h5>`

请问这个怎么解决啊？我感觉是这版代码有问题。。。

**Comment by Hasal** [comment]
是代码有问题，由于我提交错了版本，所以导致代码跑不起来。现在我已经更新代码，请尝试新的代码。多谢你的提醒。
